name: deploy-static-site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H 54.159.69.109 >> ~/.ssh/known_hosts
      - name: Copy files
        shell: bash
        run: scp -r ec2-user@54.159.69.109:/var/www src
#        run: rsync ./src/ ec2-user@54.159.69.109:/var/www
