name: deploy-static-site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy files
        shell: bash
        run: 'echo "$PRIVATE_KEY" > key.cert'
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      - name: Copy files
        shell: bash
        run: scp -r -i ./key.cert ec2-user@54.159.69.109:/var/www src
